defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: kitchenDev

test:
  <<: *defaults
  database: kitchenTest

# set these environment variables on your prod server
production:
  <<: *defaults
  database: mongoKitchen
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
